// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgophHwh_BX2cb9senqfEV0d0udjcgu-A',
    appId: '1:544983233000:android:e597783526bed7d86ef45d',
    messagingSenderId: '544983233000',
    projectId: 'flutter-prep-6b32e',
    databaseURL: 'https://flutter-prep-6b32e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6b32e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCticn9arJyfBBO5_tE9pD_uMai2Gv6Gqo',
    appId: '1:544983233000:ios:02980658ce14cba16ef45d',
    messagingSenderId: '544983233000',
    projectId: 'flutter-prep-6b32e',
    databaseURL: 'https://flutter-prep-6b32e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-6b32e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
